# .circleci/config.yml
version: 2.1

executors:
  node-executor:
    docker:
      - image: mcr.microsoft.com/playwright:latest
    working_directory: ~/playwright-tests

jobs:
  install-dependencies:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm i -D @playwright/test
      - run: 
          name: Install Playwright Browsers
          command: npx playwright install

  run-playwright-tests:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Run Playwright Tests
          command: npx playwright test

# Invoke jobs via workflows
workflows:
  run-test-workflow:
    jobs:
      - install-dependencies
      - run-playwright-tests:
          requires:
            - install-dependencies