version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:22.12.0-browsers
    working_directory: ~/playwright-tests

jobs:
  install-dependencies:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Install Playwright Browsers
          command: npx playwright install

  run-playwright-tests:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Run Playwright Tests
          command: npx playwright test

workflows:
  test-workflow:
    jobs:
      - install-dependencies:
          filters:
            branches:
              only:
                - feature/login-page
      - run-playwright-tests:
          requires:
            - install-dependencies
          filters:
            branches:
              only:
                - feature/login-page