# .circleci/config.yml
version: 2.1

executors:
  node-executor:
    docker:
      - image: mcr.microsoft.com/playwright:latest
    working_directory: ~/playwright-tests

jobs:
  run-test:
    executor: node-executor
    parallelism: 2
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm i -D @playwright/test
      - run: 
          name: Install Playwright Browsers
          command: npx playwright install
      - run:
          name: Run Playwright Tests
          command: npx playwright test --grep=login --shard=2/1
      - run:
          name: Run Playwright Tests
          command: npx playwright test --grep=signup --shard=2/2

workflows:
  run-test-workflow:
    jobs:
      - run-test:
          filters:
            branches:
              only:
                - feature/login-page